builds:
  - main: main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

    ignore:
      - goos: windows
        goarch: arm64
      - goos: linux
        goarch: arm64

    env:
      - CGO_ENABLED=0

    ldflags: -s -w -X github.com/hellofresh/klepto/cmd.version={{.Version}}
