---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: ""

inputs:
  - name: source-code
  - name: version

outputs:
  - name: build

run:
  path: ./ci/scripts/build.sh
  dir: source-code
