---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine
    tag: "latest"

inputs:
  - name: source-code
  - name: build

outputs:
  - name: archive

run:
  path: ../source-code/ci/scripts/jetstream/archive.sh
  dir: build
