---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: quay.io/hellofresh/scm-concourse-file-checker
    tag: "latest"

inputs:
  - name: source-code

run:
  path: ./ci/scripts/jetstream/check-files.sh
  dir: source-code
