---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: quay.io/hellofresh/scm-concourse-code-style-go
    tag: "latest"

inputs:
  - name: source-code

run:
  path: ./ci/scripts/jetstream/code-style.sh
  dir: source-code
