---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: quay.io/hellofresh/scm-concourse-docker-compose

inputs:
  - name: source-code

run:
  path: docker-down
  dir: source-code

