---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: quay.io/hellofresh/scm-concourse-helper-shell
    tag: "latest"

inputs:
  - name: source-code

outputs:
  - name: draft-version

run:
  path: ./ci/scripts/jetstream/draft-version.sh
  dir: source-code
