---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: quay.io/hellofresh/scm-concourse-semver
    tag: "latest"

inputs:
  - name: source-code
  - name: version

outputs:
  - name: release-version

run:
  path: version-bump
  dir: source-code
